apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-metrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-metrics-exporter
  template:
    metadata:
      labels:
        app: my-metrics-exporter
    spec:
      containers:
      - image: rodrigoeliassanchezvu/ruby-metrics-api
        name: my-metrics-exporter
        ports:
        - containerPort: 6443
        command: ["/bin/sh","-c"]
        args: ["bundle exec puma -b 'ssl://0.0.0.0:6443?key=server.key&cert=server.cert' config.ru"]
        # workingDir: /
        #args: ["bundle exec rackup --host 0.0.0.0 -p 6443"]
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
      # nodeName: group-12-node-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-metrics
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        # command: ["/bin/sh","-c"]
        # args: ["apt-get update && apt-get install -y curl"]

---

apiVersion: v1
kind: Service
metadata:
  name: my-metrics-exporter
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 6443 
  selector:
    app: my-metrics-exporter