apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: simple-pod-metrics-python
spec:
  template:
    spec:
      containers:
      - name: simple-pod-metrics-python
        image: "{{ .Values.cpa.image.repository }}:{{ .Values.cpa.image.tag }}"
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}
  config:
    - name: interval
      value: "10000"
