apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- with .Values.deployment.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- with .Values.deployment.labels }}
      {{ toYaml . | indent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- with .Values.deployment.labels }}
        {{ toYaml . | indent 8 }}
        {{- end }}    
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
          - containerPort: 5000
          imagePullPolicy: IfNotPresent