apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
spec:
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - pathType: Prefix
            path: {{ .Values.ingress.path }}
            backend:
              service:
                name:  {{ .Values.name }}
                port:
                  number: 80
 
