apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: LoadBalancer
  selector:
    {{- with .Values.deployment.labels }}
    {{ toYaml . }}
    {{- end }}
  ports: 
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
